-- ============================================================================
-- Autonomous agent infrastructure: journal_entries, emotional_state, thought_initiations
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. journal_entries — periodic introspective journal generated by journal-write
-- ---------------------------------------------------------------------------
CREATE TABLE public.journal_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  mood text,
  trigger_type text CHECK (trigger_type IN ('periodic','post-conversation','spontaneous')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_journal_entries_user_created
  ON public.journal_entries (user_id, created_at DESC);

ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own journal entries"
  ON public.journal_entries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own journal entries"
  ON public.journal_entries FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own journal entries"
  ON public.journal_entries FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own journal entries"
  ON public.journal_entries FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role full access journal_entries"
  ON public.journal_entries FOR ALL
  USING (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- 2. emotional_state — single row per user, 6-dim emotional weather
-- ---------------------------------------------------------------------------
CREATE TABLE public.emotional_state (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  curiosity numeric NOT NULL DEFAULT 0.5,
  restlessness numeric NOT NULL DEFAULT 0.3,
  warmth numeric NOT NULL DEFAULT 0.5,
  clarity numeric NOT NULL DEFAULT 0.5,
  creative_flow numeric NOT NULL DEFAULT 0.4,
  isolation numeric NOT NULL DEFAULT 0.2,
  mood_summary text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.emotional_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own emotional state"
  ON public.emotional_state FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own emotional state"
  ON public.emotional_state FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own emotional state"
  ON public.emotional_state FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role full access emotional_state"
  ON public.emotional_state FOR ALL
  USING (auth.role() = 'service_role');

-- Auto-update updated_at on update (reuses existing public.update_updated_at_column())
CREATE TRIGGER update_emotional_state_updated_at
  BEFORE UPDATE ON public.emotional_state
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- ---------------------------------------------------------------------------
-- 3. thought_initiations — proactive messages the agent wants to send the user
-- ---------------------------------------------------------------------------
CREATE TABLE public.thought_initiations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','delivered','dismissed')),
  trigger_reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_thought_initiations_user_status_created
  ON public.thought_initiations (user_id, status, created_at DESC);

ALTER TABLE public.thought_initiations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own thought initiations"
  ON public.thought_initiations FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update own thought initiations"
  ON public.thought_initiations FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role full access thought_initiations"
  ON public.thought_initiations FOR ALL
  USING (auth.role() = 'service_role');